"""F.2 — commit_helper: open a draft PR with the orchestrator's outputs.

After orchestrate.orchestrate finalizes, this helper:

1. Checks out a new branch ``auto/drafted-<union_key>-<timestamp>`` off the
   configured base branch (default ``feat/path-c-and-drafter``).
2. Writes the candidate profile + extractor into the kernel paths the
   pipeline expects:
        kernel/profiles/<union_key>.yaml
        kernel/pipeline/extract_<local>.py
   (a separate module — to be wired into ``kernel/pipeline/extract.py``
    EXTRACTORS by a human reviewer; we do NOT modify ``extract.py``
    directly per the kernel-no-touch rule.)
3. Commits with a message including [DRAFTED-by-ProfileDrafterAgent].
4. Pushes the branch and opens a draft PR via ``gh pr create``.

Returns the PR URL string ``gh`` prints.

This function shells out to ``git`` + ``gh`` via subprocess. It does NOT
import GitHub SDKs. Callers should treat any non-zero exit as a transient
failure and surface it; this module does not retry.
"""

from __future__ import annotations

import datetime as _dt
import os
import re
import subprocess
from pathlib import Path
from typing import Any


def open_pr_for_drafted_union(
    union_key: str,
    profile_yaml: str,
    extractor_py: str,
    validation_result: dict[str, Any],
    base_branch: str = "feat/path-c-and-drafter",
    repo_root: str | None = None,
    dry_run: bool = False,
) -> str:
    """Open a draft PR carrying the orchestrator's outputs.

    Args:
        union_key: e.g. ``"sprinkler_fitters_120"``.
        profile_yaml: profile YAML content.
        extractor_py: extractor Python source.
        validation_result: dict returned by validate.validate_generated.
        base_branch: PR base branch (default ``feat/path-c-and-drafter``).
        repo_root: explicit repo root; defaults to the one containing this
            file's ancestor with a ``.git/``.
        dry_run: when True, perform git operations but skip ``gh pr create``
            and return the simulated PR URL. Used by tests.

    Returns:
        The PR URL string printed by ``gh pr create``.
    """
    root = Path(repo_root) if repo_root else _find_repo_root()
    if root is None:
        raise RuntimeError("could not locate a .git/ repo root from commit_helper")

    timestamp = _dt.datetime.utcnow().strftime("%Y%m%d-%H%M%S")
    branch = f"auto/drafted-{union_key}-{timestamp}"

    local = _local(union_key)
    profile_path = root / "kernel" / "profiles" / f"{union_key}.yaml"
    extractor_path = root / "kernel" / "pipeline" / f"extract_{local}.py"

    # 1) new branch off base_branch.
    _run(["git", "checkout", "-b", branch, base_branch], cwd=root)

    # 2) write artifacts.
    profile_path.parent.mkdir(parents=True, exist_ok=True)
    extractor_path.parent.mkdir(parents=True, exist_ok=True)
    profile_path.write_text(profile_yaml, encoding="utf-8")
    extractor_path.write_text(extractor_py, encoding="utf-8")

    # 3) commit.
    _run(["git", "add", str(profile_path), str(extractor_path)], cwd=root)
    body = _commit_message(union_key, validation_result)
    _run(["git", "commit", "-m", body], cwd=root)

    # 4) push + open PR.
    _run(["git", "push", "-u", "origin", branch], cwd=root)

    pr_title = f"[DRAFTED] {union_key} profile + extractor"
    pr_body = _pr_body(union_key, validation_result)

    if dry_run:
        return f"https://github.com/EXAMPLE/laboraid-rate-engine/pull/dry-run-{branch}"

    out = _run(
        [
            "gh",
            "pr",
            "create",
            "--draft",
            "--base",
            base_branch,
            "--head",
            branch,
            "--title",
            pr_title,
            "--body",
            pr_body,
        ],
        cwd=root,
        capture=True,
    )
    return _extract_pr_url(out)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _commit_message(union_key: str, validation_result: dict[str, Any]) -> str:
    accuracy = float(validation_result.get("accuracy_pct", 0.0))
    return (
        f"feat({union_key}): auto-drafted profile + extractor "
        f"({accuracy:.1f}% on documented cells) [DRAFTED-by-ProfileDrafterAgent]\n"
        f"\n"
        f"* kernel/profiles/{union_key}.yaml — schema-validated\n"
        f"* kernel/pipeline/extract_{_local(union_key)}.py — codegen-validated\n"
        f"\n"
        f"Generated by ProfileDrafterAgent (Spec/09 §15.1). Review before "
        f"merging; the EXTRACTORS table in kernel/pipeline/extract.py must "
        f"be wired by hand (kernel-no-touch rule for the subtree).\n"
    )


def _pr_body(union_key: str, validation_result: dict[str, Any]) -> str:
    accuracy = float(validation_result.get("accuracy_pct", 0.0))
    mismatches = int(validation_result.get("mismatch_count", 0))
    return (
        f"## Drafted union: `{union_key}`\n\n"
        f"Auto-generated by ProfileDrafterAgent (Spec/09 §15.1, "
        f"docs/BUILD_PROFILE_DRAFTER.md).\n\n"
        f"### Validation\n\n"
        f"* schema_pass: `{validation_result.get('schema_pass')}`\n"
        f"* codegen_pass: `{validation_result.get('codegen_pass')}`\n"
        f"* syntax_pass: `{validation_result.get('syntax_pass')}`\n"
        f"* accuracy_pct: `{accuracy:.1f}%`\n"
        f"* mismatch_count: `{mismatches}`\n\n"
        f"### Reviewer checklist\n\n"
        f"- [ ] Eyeball the profile YAML for canonical-field correctness.\n"
        f"- [ ] Skim the extractor Python — does it match the 704/483 pattern?\n"
        f"- [ ] Wire `extract_{_local(union_key)}` into "
        f"`kernel/pipeline/extract.py`'s `EXTRACTORS` table (the drafter does "
        f"not edit the kernel subtree).\n"
        f"- [ ] Run `uv run python kernel/pipeline/run.py --union {union_key}` "
        f"to confirm the evaluator agrees with the drafter's reported accuracy.\n"
    )


def _extract_pr_url(gh_output: str) -> str:
    """Find the github.com/.../pull/<n> URL in gh's stdout."""
    m = re.search(r"https?://github\.com/[\w./-]+/pull/\d+", gh_output)
    return m.group(0) if m else gh_output.strip()


def _find_repo_root() -> Path | None:
    cur = Path(__file__).resolve()
    for parent in (cur, *cur.parents):
        if (parent / ".git").exists():
            return parent
    return None


def _local(union_key: str) -> str:
    if "_" not in union_key:
        return union_key
    return union_key.rsplit("_", 1)[-1]


def _run(
    cmd: list[str],
    cwd: Path,
    capture: bool = False,
) -> str:
    """Run a subprocess and raise on non-zero exit. Returns stdout if capture."""
    proc = subprocess.run(
        cmd,
        cwd=str(cwd),
        capture_output=True,
        text=True,
        env={**os.environ},
    )
    if proc.returncode != 0:
        raise RuntimeError(
            f"command {cmd!r} failed (exit {proc.returncode}): "
            f"stdout={proc.stdout!r} stderr={proc.stderr!r}"
        )
    return proc.stdout if capture else ""
